export const GET_QUERY_RESULTS = "GET_QUERY_RESULTS";
export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const GET_QUERIES = "GET_QUERIES";